site_name: MCI Coding Manual
site_url: https://mckoh.github.io/coding
docs_dir: docs_source
site_dir: docs
nav:
  - Home: index.md
  - About: about.md
  - Exercise: exercises.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences