site_name: MCI Coding Manual
site_url: https://mckoh.github.io/coding
docs_dir: docs_source
site_dir: docs

nav:
  - Home: index.md
  - About: about.md
  - Exercise:
    - Overview: exercises.md
    - Exercise 1: exercise_01.md
    - Exercise 2: exercise_02.md
    - Exercise 3: exercise_03.md

theme:
  name: material
  logo: img/logo_coding.png
  features:
    - content.code.copy
  palette:
    primary: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight