site_name: Coding Manual
site_url: https://mckoh.github.io/coding
docs_dir: docs_source
site_dir: docs

nav:
  - Home: index.md
  - About: about.md
  - Exercise: exercises.md
  - Solutions: solutions.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/code
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
  color_mode: dark
  palette:
    primary: indigo # teal
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

extra:
  copyright: Copyright &copy; 2024 - 2020 Michael Kohlegger
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mckoh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight